# Generated by Django 6.1.1 on 2026-10-05 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_app', '0003_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.CreateModel(
            name='producto_categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos_app.categoria')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos_app.producto')),
            ],
        ),
    ]
